### PR TITLE
Respawn Settings/Listbox Checkboxes

### PR DESCRIPTION
**Pull request by thecogdoctor**
These changes fix the Respawn Settings List-box and inner check-boxes.
It also includes all recent changes to master branch to bring dev more in-line with master.

Needs dedicated MP testing before merging.

### CODE REVIEW

**Comment by thecogdoctor** [comment]
At the moment:
1. Issues with re-spawning when Unlimited Respawns is enabled have been observed.
  * Actually being respawned not occurring to being stuck in the "YOU ARE DEAD" screen.
2. Ticketed respawns do not work and will instantly send the player to spectator mode.
3. ... (TBD)

More issues will be reported as time goes on.

**Comment by ChrSacher** [comment]
Properties for the Spectator Settings are wrong.
Many properties are Spectate instead of Spectator.
Spectate needs to be replaced by Spectator.

OPFOR should be Opfor

**Comment by thecogdoctor** [comment]
We really need to standardize our faction strings...

**Comment by ChrSacher** [comment]
L 180
fn_spectate.sqf
_pos getpos [-2, _dir];
this should be
_pos = _pos getpos [-2, _dir];

**Comment by thecogdoctor** [comment]
> 
> 
> L 180
> fn_spectate.sqf
> _pos getpos [-2, _dir];
> this should be
> _pos = _pos getpos [-2, _dir];

Fixed in 78b33a59ae611bd29294f4c32b3b185a972c84d0

**Comment by thecogdoctor** [comment]
While testing was being conducted the individual ticket system was found to not be working.

**Pull request merged**
