### PR TITLE
Addition of a formal license

### PR DESCRIPTION
**Pull request by thecogdoctor**
Proposal of addition of the APL-SA License to the United Operations Framework.
Other potential licenses for consideration; GPLV2.0, BSD 2-Clause or MIT License.
I would highly suggest either the proposed APL-SA or GPLV2.0 as they ensure us the best reusable nature for ourselves and other communities.
While not optimal I think the GPLV3.0 could be considered but I am lukewarm on some of it's considerations regarding redistribution as a commercial product.

Edit: Clarified my statement on GPLV3.0 to better reflect my intent.

### CODE REVIEW

**Comment by PiZZAD0X** [comment]
I'd say this is best made @Impulse-9 's decision, considering we are using UO's name. My opinion is that modding is a labour of love and shouldn't even need licensing and that any derivatives and modifications should be allowed and encouraged. Putting our names on functions and modules shouldn't be for credit but for reference and getting help on subsequent work on it.

**Comment by thecogdoctor** [comment]
> 
> 
> I'd say this is best made @Impulse-9 's decision, 

Of course, that is a totally fair point.
>
>
>considering we are using UO's name. My opinion is that modding is a labour of love and shouldn't even need licensing and that any derivatives and modifications should be allowed and encouraged. 

This will be provided under the Share-Alike license, MIT, BSD 2-Clause or any GPL variant. 
If you read into the legal and other related consequences of having no official license, you understand that it is likely to cause issues for developers, contributors and anyone else down the line. Simply reference Github's page on licensing for more background info on this.<br/>
I feel strongly we need to put a license on our code in some form in order to properly give our code to anyone who would use it, including United Operations and ourselves as developers. These full legal rights to modify and change our own work, and for others to do the same are important and need to be clearly laid out. This is what the licensing does for us as developers.

>
>
>Putting our names on functions and modules shouldn't be for credit but for reference and getting help on subsequent work on it. 

I don't see it this way but I can understand where you're coming from. I would prefer that credit is given where it is due as we are using our free time to contribute to this and any other open-source projects with the exception of a few niche corporate projects.

A quick note in regards to monetization, I would prefer that it is not allowed, specifically in the way disallowed under the APL-SA but as the final license is ultimately decided by @Impulse-9  I will merely voice my concerns and opinions here in this original thread.

**Comment by BlackHawkPL** [comment]
If it's up to me it's MIT. But IMO it's up to Impulse since he's owner of the Unitedoperations®™©.

**Comment by thecogdoctor** [comment]
> 
> 
> If it's up to me it's MIT. But IMO it's up to Impulse since he's owner of the Unitedoperations®™©.

With that in mind, @Impulse-9 when you have the opportunity please leave a formal review. This isn't as important at the current moment, but as the project nears feature complete, a license will need to be selected. I am airing on the side of MIT myself.

**Comment by thecogdoctor** [comment]
I would like to propose licensing the framework under the GPLv2 license and the inclusion of the MIT License in a usage disclosure folder for any and all code within the framework that remains from the Olsen Framework.

I will add a commit later today with both of those changes. to this PR. Unless any major objections are raised this should be our final action in regards to licensing the framework.

**Pull request merged**
